# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      #- id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
        exclude: \.(devcontainer|vscode).*
      - id: check-yaml
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      # - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args:
          - --toml-config=pyproject.toml
        language: python
        types: [python]
        pass_filenames: true
        require_serial: true
      - id: pylint
        name: pylint
        entry: pylint
        args:
          - --rcfile=pyproject.toml
        language: python
        types: [python]
        pass_filenames: true
        require_serial: true
      - id: black
        name: black
        entry: black
        args:
          - --check
          - --diff
        language: python
        types: [python]
        pass_filenames: true
        require_serial: true

  # - repo: https://github.com/asottile/dead
  #   rev: v1.5.0
  #   hooks:
  #       - id: dead
