version: '3.7'

services:
  pioneer:
    build: .
    restart: always
    # environment:
    #   PIONEER_CONFIG_PATH: /config/pioneer_config.json
    ports:
      # Sync with devcontainer.json
      - 9091:9091
    volumes:
      - ./test:/pioneer/test
      # - ./config:/config
